# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Blogs
    url: /blog
    weight: 20
  - name: Projects
    url: /projects
    weight: 30
  - name: Study Notes
    url: /study
    weight: 40
  - name: Information
    weight: 50
    hasChildren: true
  - parent: Information
    name: about me
    weight: 60
    url: about/
  - parent: Information
    name: contact
    weight: 70
    url: contact/

